export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;
export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


export const INCREMENT_NUMBERS = 'INCREMENT_NUMBERS';
export type INCREMENT_NUMBERS = typeof INCREMENT_NUMBERS;
export const DECREMENT_NUMBERS = 'DECREMENT_NUMBERS';
export type DECREMENT_NUMBERS = typeof DECREMENT_NUMBERS;